#!/usr/bin/env python3.6
"""Evaluates all 9 CNN models (3 tasks × 3 planes) and generates a report.

Usage:
  evaluate_all_models.py <predictions_dir> <data_paths_csv> <labels_csv> [--loss-weight=<w>] [--threshold=<t>] [--use-calculated-threshold] [--output-dir=<dir>]
  evaluate_all_models.py (-h | --help)

General options:
  -h --help                   Show this screen.

Arguments:
  <predictions_dir>           Directory containing prediction csv files generated by
                              src/predict_all_models.py
                              e.g. 'out'
  <data_paths_csv>            csv file listing paths to dataset samples (in same order as predictions)
                              e.g. 'test_split1_paths.csv'
  <labels_csv>                csv file containing labels for the dataset
                              e.g. 'MRNet-v1.0/test_split1_labels.csv'

Options:
  --loss-weight=<w>           Positive weight for BCEWithLogitsLoss [default: 1.0]
  --threshold=<t>             Fixed probability threshold for all models (e.g. 0.5). If omitted,
                              the script uses 0.5 by default unless --use-calculated-threshold is passed.
  --use-calculated-threshold  Use the model-specific Youden J threshold instead of a fixed threshold.
  --output-dir=<dir>          Directory where the Excel summary will be saved [default: .]
"""

import os
import sys
import glob
from docopt import docopt

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from sklearn import metrics


def evaluate_model(predictions, labels, loss_weight=1.0, threshold=None, use_calculated_threshold=False):
    """Calculate all metrics for a single model.

    Args:
        predictions: model logits for the samples
        labels: true binary labels
        loss_weight: BCEWithLogitsLoss positive class weight
        threshold: optional fixed probability threshold to use for classification.
                   If None and not use_calculated_threshold, defaults to 0.5.
        use_calculated_threshold: if True, use the model-specific Youden J threshold.
    """
    
    # Ensure same length
    if len(predictions) != len(labels):
        min_len = min(len(predictions), len(labels))
        predictions = predictions[:min_len]
        labels = labels[:min_len]

    # Convert logits to probabilities using sigmoid
    probs = 1 / (1 + np.exp(-predictions))

    # Calculate AUC
    auc = metrics.roc_auc_score(labels, predictions)

    # Calculate Loss (BCEWithLogitsLoss)
    pos_weight = torch.tensor([loss_weight])
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    preds_tensor = torch.tensor(predictions, dtype=torch.float32)
    labels_tensor = torch.tensor(labels, dtype=torch.float32)
    loss = criterion(preds_tensor, labels_tensor).item()

    # Calculate threshold (optimal using Youden's J statistic)
    fpr, tpr, thresholds = metrics.roc_curve(labels, predictions)
    youden_j = tpr - fpr
    optimal_idx = np.argmax(youden_j)
    optimal_threshold = thresholds[optimal_idx]
    optimal_threshold_prob = 1 / (1 + np.exp(-optimal_threshold))

    # Select decision threshold
    if use_calculated_threshold:
        decision_threshold = optimal_threshold_prob
    elif threshold is not None:
        decision_threshold = float(threshold)
    else:
        decision_threshold = 0.5

    # Get binary predictions using the selected threshold on probabilities
    binary_preds = (probs >= decision_threshold).astype(int)

    # Calculate Sensitivity (True Positive Rate)
    sensitivity = metrics.recall_score(labels, binary_preds)

    # Calculate Specificity (True Negative Rate)
    tn, fp, fn, tp = metrics.confusion_matrix(labels, binary_preds).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0

    # Calculate Accuracy
    accuracy = metrics.accuracy_score(labels, binary_preds)

    return {
        'auc': auc,
        'loss': loss,
        'sensitivity': sensitivity,
        'specificity': specificity,
        'accuracy': accuracy,
        'threshold': decision_threshold,
        'tp': tp,
        'tn': tn,
        'fp': fp,
        'fn': fn
    }


def main(predictions_dir, data_paths_csv, labels_csv, loss_weight=1.0, threshold=None, use_calculated_threshold=False, output_dir='.'):
    print('Evaluating all models...\n')

    # Load data paths
    print(f'Loading data paths from {data_paths_csv}...')
    all_paths = []
    with open(data_paths_csv, 'r') as f:
        all_paths = [line.strip() for line in f.readlines()]
    
    print(f'Total sample paths: {len(all_paths)}')

    # Load labels
    print(f'Loading labels from {labels_csv}...')
    labels_df = pd.read_csv(labels_csv)
    print(f'Labels shape: {labels_df.shape}')

    # Define all models
    tasks = ['abnormal', 'acl', 'meniscus']
    planes = ['axial', 'coronal', 'sagittal']

    # Find all prediction files
    pred_files = {}
    for pred_file in glob.glob(os.path.join(predictions_dir, 'predictions_*.csv')):
        filename = os.path.basename(pred_file)
        # Extract task and plane: predictions_<task>_<plane>.csv
        parts = filename.replace('predictions_', '').replace('.csv', '').split('_')
        if len(parts) >= 2:
            task = parts[0]
            plane = parts[1]
            pred_files[(task, plane)] = pred_file

    if not pred_files:
        print(f'Error: No prediction files found in {predictions_dir}')
        return

    # Dictionary to store results
    results = {}

    print('=' * 120)
    print(f'{"Task":<15} {"Plane":<12} {"AUC":<10} {"Loss":<10} {"Sensitivity":<15} {"Specificity":<15} {"Accuracy":<10} {"Threshold":<10}')
    print('=' * 120)

    # Evaluate each model
    for task, plane in [(t, p) for t in tasks for p in planes]:
        key = (task, plane)
        
        if key not in pred_files:
            print(f'Warning: Predictions for {task} ({plane}) not found')
            continue

        # Load predictions for this model's plane
        preds_df = pd.read_csv(pred_files[key], header=None)
        plane_predictions = preds_df.values.flatten().astype(np.float32)

        # Get labels for this task
        label_column = task
        if label_column not in labels_df.columns:
            print(f'Warning: Label column "{label_column}" not found in {labels_csv}')
            continue

        # Filter paths to get only this plane's indices
        plane_paths = [p for p in all_paths if f'/{plane}/' in p]
        
        # Extract cases from plane paths
        cases = []
        for path in plane_paths:
            # Extract case number from path: .../XXXX.npy
            case_num = os.path.basename(path).replace('.npy', '')
            cases.append(case_num)

        # Get labels for these cases
        labels_list = []
        for case in cases:
            case_row = labels_df[labels_df.case == int(case)]
            if len(case_row) > 0:
                labels_list.append(case_row[label_column].values[0])
            else:
                print(f'Warning: Case {case} not found in labels')

        predictions = np.array(plane_predictions, dtype=np.float32)
        labels = np.array(labels_list, dtype=np.float32)

        # Verify lengths match
        if len(predictions) != len(labels):
            print(f'Warning: Mismatch for {task} ({plane}): {len(predictions)} predictions vs {len(labels)} labels')
            min_len = min(len(predictions), len(labels))
            predictions = predictions[:min_len]
            labels = labels[:min_len]

        # Evaluate
        metrics_dict = evaluate_model(
            predictions,
            labels,
            loss_weight=loss_weight,
            threshold=threshold,
            use_calculated_threshold=use_calculated_threshold
        )
        results[key] = metrics_dict

        # Print results
        print(f'{task:<15} {plane:<12} {metrics_dict["auc"]:<10.4f} {metrics_dict["loss"]:<10.4f} '
              f'{metrics_dict["sensitivity"]:<15.4f} {metrics_dict["specificity"]:<15.4f} {metrics_dict["accuracy"]:<10.4f} {metrics_dict["threshold"]:<10.4f}')

    print('=' * 100)

    # Print detailed results for each model
    print('\n\nDETAILED RESULTS:')
    print('=' * 100)

    for task, plane in [(t, p) for t in tasks for p in planes]:
        key = (task, plane)
        if key not in results:
            continue

        m = results[key]
        print(f'\n{task.upper()} - {plane.upper()} PLANE:')
        print(f'  AUC:         {m["auc"]:.4f}')
        print(f'  Loss:        {m["loss"]:.4f}')
        print(f'  Sensitivity: {m["sensitivity"]:.4f}')
        print(f'  Specificity: {m["specificity"]:.4f}')
        print(f'  Accuracy:    {m["accuracy"]:.4f}')
        print(f'  Threshold:   {m["threshold"]:.4f}')
        print(f'  TP: {m["tp"]:<5} TN: {m["tn"]:<5} FP: {m["fp"]:<5} FN: {m["fn"]:<5}')

    # Summary statistics
    print('\n\n' + '=' * 100)
    print('SUMMARY STATISTICS:')
    print('=' * 100)

    if results:
        aucs = [m['auc'] for m in results.values()]
        losses = [m['loss'] for m in results.values()]
        sensitivities = [m['sensitivity'] for m in results.values()]
        specificities = [m['specificity'] for m in results.values()]
        accuracies = [m['accuracy'] for m in results.values()]

        print(f'AUC:         Mean: {np.mean(aucs):.4f} ± {np.std(aucs):.4f} | Min: {np.min(aucs):.4f} | Max: {np.max(aucs):.4f}')
        print(f'Loss:        Mean: {np.mean(losses):.4f} ± {np.std(losses):.4f} | Min: {np.min(losses):.4f} | Max: {np.max(losses):.4f}')
        print(f'Sensitivity: Mean: {np.mean(sensitivities):.4f} ± {np.std(sensitivities):.4f} | Min: {np.min(sensitivities):.4f} | Max: {np.max(sensitivities):.4f}')
        print(f'Specificity: Mean: {np.mean(specificities):.4f} ± {np.std(specificities):.4f} | Min: {np.min(specificities):.4f} | Max: {np.max(specificities):.4f}')
        print(f'Accuracy:    Mean: {np.mean(accuracies):.4f} ± {np.std(accuracies):.4f} | Min: {np.min(accuracies):.4f} | Max: {np.max(accuracies):.4f}')

    if results:
        excel_rows = []
        for (task, plane), metrics_dict in results.items():
            excel_rows.append({
                'task': task,
                'plane': plane,
                'auc': metrics_dict['auc'],
                'loss': metrics_dict['loss'],
                'sensitivity': metrics_dict['sensitivity'],
                'specificity': metrics_dict['specificity'],
                'accuracy': metrics_dict['accuracy'],
                'threshold': metrics_dict['threshold'],
                'tp': metrics_dict['tp'],
                'tn': metrics_dict['tn'],
                'fp': metrics_dict['fp'],
                'fn': metrics_dict['fn']
            })

        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

        excel_path = os.path.join(output_dir, 'all_models_metrics.xlsx')
        pd.DataFrame(excel_rows).to_excel(excel_path, index=False)
        print(f'Excel summary saved to {excel_path}')


if __name__ == '__main__':
    arguments = docopt(__doc__)

    print('Parsing arguments...')

    loss_weight = float(arguments['--loss-weight']) if arguments['--loss-weight'] is not None else 1.0
    threshold = float(arguments['--threshold']) if arguments['--threshold'] is not None else None
    use_calculated_threshold = bool(arguments['--use-calculated-threshold'])
    output_dir = arguments['--output-dir'] if arguments['--output-dir'] is not None else '.'

    main(arguments['<predictions_dir>'],
         arguments['<data_paths_csv>'],
         arguments['<labels_csv>'],
         loss_weight,
         threshold=threshold,
         use_calculated_threshold=use_calculated_threshold,
         output_dir=output_dir)
