#!/usr/bin/env python3.6
"""Calculates evaluation metrics (AUC, loss, sensitivity, specificity, accuracy)
for a single model on a given dataset.

Usage:
  evaluate_single_model.py <preds_csv> <labels_csv> [--loss-weight=<w>]
  evaluate_single_model.py (-h | --help)

General options:
  -h --help          Show this screen.

Arguments:
  <preds_csv>        csv file generated by src/predict_single_model.py
                     containing model predictions
                     e.g. 'out_dir/predictions_single.csv'
  <labels_csv>       csv file containing labels for the dataset
                     e.g. 'MRNet-v1.0/valid_labels.csv'

Options:
  --loss-weight=<w>  Positive weight for BCEWithLogitsLoss [default: 1.0]
"""

import os
import sys
from docopt import docopt

import pandas as pd
import numpy as np
import torch
import torch.nn as nn

from sklearn import metrics


def main(preds_csv, labels_csv, loss_weight=1.0):
    print('Calculating evaluation metrics...')

    # Load predictions
    preds_df = pd.read_csv(preds_csv, header=None)
    predictions = preds_df.values.flatten().astype(np.float32)

    # Load labels
    labels_df = pd.read_csv(labels_csv)
    
    # Extract the first diagnosis label column (usually 'abnormal', 'acl', or 'meniscus')
    # Assuming the labels_df has structure like: case, diagnosis1, diagnosis2, diagnosis3
    # We take the first diagnosis column
    label_column = labels_df.columns[1]  # Skip 'case' column
    labels = labels_df[label_column].values.astype(np.float32)

    # Ensure predictions and labels have the same length
    if len(predictions) != len(labels):
        print(f'Warning: Number of predictions ({len(predictions)}) does not match labels ({len(labels)})')
        min_len = min(len(predictions), len(labels))
        predictions = predictions[:min_len]
        labels = labels[:min_len]

    # Convert logits to probabilities using sigmoid
    probs = 1 / (1 + np.exp(-predictions))

    # Calculate AUC
    auc = metrics.roc_auc_score(labels, predictions)

    # Calculate Loss (BCEWithLogitsLoss)
    pos_weight = torch.tensor([loss_weight])
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    preds_tensor = torch.tensor(predictions, dtype=torch.float32)
    labels_tensor = torch.tensor(labels, dtype=torch.float32)
    loss = criterion(preds_tensor, labels_tensor).item()

    # Calculate threshold (optimal using Youden's J statistic)
    fpr, tpr, thresholds = metrics.roc_curve(labels, predictions)
    youden_j = tpr - fpr
    optimal_idx = np.argmax(youden_j)
    optimal_threshold = thresholds[optimal_idx]

    # Get binary predictions using optimal threshold
    binary_preds = (predictions >= optimal_threshold).astype(int)

    # Calculate Sensitivity (True Positive Rate)
    sensitivity = metrics.recall_score(labels, binary_preds)

    # Calculate Specificity (True Negative Rate)
    tn, fp, fn, tp = metrics.confusion_matrix(labels, binary_preds).ravel()
    specificity = tn / (tn + fp)

    # Calculate Accuracy
    accuracy = metrics.accuracy_score(labels, binary_preds)

    # Print results
    print(f'\n=== Evaluation Metrics ===')
    print(f'  AUC:         {auc:.4f}')
    print(f'  Loss:        {loss:.4f}')
    print(f'  Sensitivity: {sensitivity:.4f}')
    print(f'  Specificity: {specificity:.4f}')
    print(f'  Accuracy:    {accuracy:.4f}')
    print(f'\n  Optimal Threshold: {optimal_threshold:.4f}')
    print(f'  True Positives:  {tp}')
    print(f'  True Negatives:  {tn}')
    print(f'  False Positives: {fp}')
    print(f'  False Negatives: {fn}')


if __name__ == '__main__':
    arguments = docopt(__doc__)

    print('Parsing arguments...')

    loss_weight = float(arguments['--loss-weight']) if arguments['--loss-weight'] is not None else 1.0

    main(arguments['<preds_csv>'],
         arguments['<labels_csv>'],
         loss_weight)
