#!/usr/bin/env python3.6
"""Calculates the average AUC score of the abnormality detection, ACL tear and
Meniscal tear tasks, along with additional metrics (sensitivity, specificity, accuracy, loss).

Usage:
  evaluate_moremetrics.py <valid_paths_csv> <preds_csv> <valid_labels_csv> [--loss-weight=<w>]
  evaluate_moremetrics.py (-h | --help)

General options:
  -h --help          Show this screen.

Arguments:
  <valid_paths_csv>    csv file listing paths to validation set, which needs to
                       be in a specific order - an example is provided as
                       valid-paths.csv in the root of the project
                       e.g. 'valid-paths.csv'
  <preds_csv>          csv file generated by src/predict.py
                       e.g. 'out_dir/predictions.csv'
  <valid_labels_csv>   csv file containing labels for the valid dataset
                       e.g. 'MRNet-v1.0/valid_labels.csv'

Options:
  --loss-weight=<w>  Positive weight for BCEWithLogitsLoss [default: 1.0]
"""

import os
import sys
import csv
from docopt import docopt

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

from sklearn import metrics


def plot_roc_curves(results, diagnoses):
    """Generate and save ROC curves for each diagnosis."""
    n_diagnoses = len(diagnoses)
    
    # Create subplots
    fig, axes = plt.subplots(1, n_diagnoses, figsize=(5 * n_diagnoses, 4))
    
    # Handle single diagnosis case
    if n_diagnoses == 1:
        axes = [axes]
    
    for idx, diagnosis in enumerate(diagnoses):
        m = results[diagnosis]
        fpr = m['fpr']
        tpr = m['tpr']
        auc = m['auc']
        threshold = m['threshold']
        predictions = m['predictions']
        labels = m['labels']
        
        # Plot ROC curve
        axes[idx].plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {auc:.4f})')
        axes[idx].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Random classifier')
        
        # Find optimal threshold point on ROC curve using Youden's J
        youden_j = tpr - fpr
        optimal_idx = np.argmax(youden_j)
        axes[idx].plot(fpr[optimal_idx], tpr[optimal_idx], 'ro', markersize=8, 
                      label=f'Optimal threshold = {threshold:.4f}')
        
        axes[idx].set_xlim([0.0, 1.0])
        axes[idx].set_ylim([0.0, 1.05])
        axes[idx].set_xlabel('False Positive Rate')
        axes[idx].set_ylabel('True Positive Rate')
        axes[idx].set_title(f'ROC Curve - {diagnosis.upper()}')
        axes[idx].legend(loc="lower right")
        axes[idx].grid(alpha=0.3)
    
    plt.tight_layout()
    plt.savefig('roc_curves.png', dpi=300, bbox_inches='tight')
    print('ROC curves saved as roc_curves.png')
    plt.close()


def calculate_metrics(predictions, labels, loss_weight=1.0):
    """Calculate all metrics for a single model."""
    
    # Ensure same length
    if len(predictions) != len(labels):
        min_len = min(len(predictions), len(labels))
        predictions = predictions[:min_len]
        labels = labels[:min_len]

    # Calculate AUC
    auc = metrics.roc_auc_score(labels, predictions)

    # Calculate Loss (BCEWithLogitsLoss)
    pos_weight = torch.tensor([loss_weight])
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    preds_tensor = torch.tensor(predictions, dtype=torch.float32)
    labels_tensor = torch.tensor(labels, dtype=torch.float32)
    loss = criterion(preds_tensor, labels_tensor).item()

    # Calculate threshold (optimal using Youden's J statistic)
    fpr, tpr, thresholds = metrics.roc_curve(labels, predictions)
    youden_j = tpr - fpr
    optimal_idx = np.argmax(youden_j)
    optimal_threshold = thresholds[optimal_idx]

    # Get binary predictions using optimal threshold
    binary_preds = (predictions >= optimal_threshold).astype(int)

    # Calculate Sensitivity (True Positive Rate)
    sensitivity = metrics.recall_score(labels, binary_preds)

    # Calculate Specificity (True Negative Rate)
    tn, fp, fn, tp = metrics.confusion_matrix(labels, binary_preds).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0

    # Calculate Accuracy
    accuracy = metrics.accuracy_score(labels, binary_preds)

    return {
        'auc': auc,
        'loss': loss,
        'sensitivity': sensitivity,
        'specificity': specificity,
        'accuracy': accuracy,
        'threshold': optimal_threshold,
        'tp': tp,
        'tn': tn,
        'fp': fp,
        'fn': fn,
        'fpr': fpr,
        'tpr': tpr,
        'predictions': predictions,
        'labels': labels
    }


def main(valid_paths_csv, preds_csv, valid_labels_csv, loss_weight=1.0):
    print('Reporting AUC scores and additional metrics...\n')

    preds_df = pd.read_csv(preds_csv, header=None)
    valid_df = pd.read_csv(valid_labels_csv)

    old_case = None

    cases = []
    with open(valid_paths_csv, 'r') as paths:
        for path in paths:
            case = os.path.splitext(os.path.basename(path.strip()))[0]
            if case == old_case:
                next
            else:
                cases.append(case)
                old_case = case

    ys = []
    Xs = []

    for i, case in enumerate(cases):
        case_row = valid_df[valid_df.case == int(case)]

        y = case_row.values[0,1:].astype(np.float32)
        ys.append(y)

        X = preds_df.iloc[i].values
        Xs.append(X)

    ys = np.asarray(ys).transpose()
    Xs = np.asarray(Xs).transpose()

    results = {}
    diagnoses = valid_df.columns.values[1:]

    print('=' * 120)
    print(f'{"Diagnosis":<15} {"AUC":<10} {"Loss":<10} {"Sensitivity":<15} {"Specificity":<15} {"Accuracy":<10} {"Threshold":<10}')
    print('=' * 120)

    for i, diagnosis in enumerate(diagnoses):
        metrics_dict = calculate_metrics(Xs[i], ys[i], loss_weight)
        results[diagnosis] = metrics_dict

        print(f'{diagnosis:<15} {metrics_dict["auc"]:<10.4f} {metrics_dict["loss"]:<10.4f} '
              f'{metrics_dict["sensitivity"]:<15.4f} {metrics_dict["specificity"]:<15.4f} '
              f'{metrics_dict["accuracy"]:<10.4f} {metrics_dict["threshold"]:<10.4f}')

    print('=' * 120)

    # Print detailed results
    print('\n\nDETAILED RESULTS:')
    print('=' * 120)

    for diagnosis in diagnoses:
        m = results[diagnosis]
        print(f'\n{diagnosis.upper()}:')
        print(f'  AUC:         {m["auc"]:.4f}')
        print(f'  Loss:        {m["loss"]:.4f}')
        print(f'  Sensitivity: {m["sensitivity"]:.4f}')
        print(f'  Specificity: {m["specificity"]:.4f}')
        print(f'  Accuracy:    {m["accuracy"]:.4f}')
        print(f'  Threshold:   {m["threshold"]:.4f}')
        print(f'  TP: {m["tp"]:<5} TN: {m["tn"]:<5} FP: {m["fp"]:<5} FN: {m["fn"]:<5}')

    # Generate ROC curves
    print('\n\nGenerating ROC curves...')
    plot_roc_curves(results, diagnoses)

    # Summary statistics
    print('\n\n' + '=' * 120)
    print('SUMMARY STATISTICS:')
    print('=' * 120)

    if results:
        aucs = [m['auc'] for m in results.values()]
        losses = [m['loss'] for m in results.values()]
        sensitivities = [m['sensitivity'] for m in results.values()]
        specificities = [m['specificity'] for m in results.values()]
        accuracies = [m['accuracy'] for m in results.values()]

        print(f'AUC:         Mean: {np.mean(aucs):.4f} ± {np.std(aucs):.4f} | Min: {np.min(aucs):.4f} | Max: {np.max(aucs):.4f}')
        print(f'Loss:        Mean: {np.mean(losses):.4f} ± {np.std(losses):.4f} | Min: {np.min(losses):.4f} | Max: {np.max(losses):.4f}')
        print(f'Sensitivity: Mean: {np.mean(sensitivities):.4f} ± {np.std(sensitivities):.4f} | Min: {np.min(sensitivities):.4f} | Max: {np.max(sensitivities):.4f}')
        print(f'Specificity: Mean: {np.mean(specificities):.4f} ± {np.std(specificities):.4f} | Min: {np.min(specificities):.4f} | Max: {np.max(specificities):.4f}')
        print(f'Accuracy:    Mean: {np.mean(accuracies):.4f} ± {np.std(accuracies):.4f} | Min: {np.min(accuracies):.4f} | Max: {np.max(accuracies):.4f}')


if __name__ == '__main__':
    arguments = docopt(__doc__)

    print('Parsing arguments...')

    loss_weight = float(arguments['--loss-weight']) if arguments['--loss-weight'] is not None else 1.0

    main(arguments['<valid_paths_csv>'],
         arguments['<preds_csv>'],
         arguments['<valid_labels_csv>'],
         loss_weight)
