#!/usr/bin/env python3.6
"""Calculates the average AUC score of the abnormality detection, ACL tear and
Meniscal tear tasks, along with additional metrics (sensitivity, specificity, accuracy, loss).

Usage:
  evaluate_moremetrics.py <valid_paths_csv> <preds_csv> <valid_labels_csv> [--loss-weight=<w>] [--output-dir=<dir>] [--threshold=<t>] [--use-calculated-threshold]
  evaluate_moremetrics.py (-h | --help)

General options:
  -h --help                   Show this screen.

Arguments:
  <valid_paths_csv>           csv file listing paths to validation set, which needs to
                              be in a specific order - an example is provided as
                              valid-paths.csv in the root of the project
                              e.g. 'valid-paths.csv'
  <preds_csv>                 csv file generated by src/predict.py
                              e.g. 'out_dir/predictions.csv'
  <valid_labels_csv>          csv file containing labels for the valid dataset
                              e.g. 'MRNet-v1.0/valid_labels.csv'

Options:
  --loss-weight=<w>           Positive weight for BCEWithLogitsLoss [default: 1.0]
  --output-dir=<dir>          Directory to save ROC curves [default: .]
  --threshold=<t>             Fixed probability threshold for all models (e.g. 0.5). If omitted,
                              the script uses 0.5 by default unless --use-calculated-threshold is passed.
  --use-calculated-threshold  Use the model-specific Youden J threshold instead of a fixed threshold.
"""

import os
import sys
import csv
from docopt import docopt

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt

from sklearn import metrics


def plot_roc_curves(results, diagnoses, output_dir='.'):
    """Generate and save ROC curves for each diagnosis."""
    # Create output directory if it doesn't exist
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    n_diagnoses = len(diagnoses)
    
    # Create subplots
    fig, axes = plt.subplots(1, n_diagnoses, figsize=(5 * n_diagnoses, 4))
    
    # Handle single diagnosis case
    if n_diagnoses == 1:
        axes = [axes]
    
    for idx, diagnosis in enumerate(diagnoses):
        m = results[diagnosis]
        fpr = m['fpr']
        tpr = m['tpr']
        auc = m['auc']
        threshold = m['threshold']
        predictions = m['predictions']
        labels = m['labels']
        
        # Plot ROC curve
        axes[idx].plot(fpr, tpr, color='darkorange', lw=2, label=f'Curva ROC (AUC = {auc:.4f})')
        axes[idx].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--', label='Clasificador aleatorio')
        
        # Find optimal threshold point on ROC curve using Youden's J
        youden_j = tpr - fpr
        optimal_idx = np.argmax(youden_j)
        axes[idx].plot(fpr[optimal_idx], tpr[optimal_idx], 'ro', markersize=8, 
                      label=f'Umbral óptimo = {threshold:.4f}')
        
        axes[idx].set_xlim([0.0, 1.0])
        axes[idx].set_ylim([0.0, 1.05])
        axes[idx].set_xlabel('1 - Especificidad (FPR)')
        axes[idx].set_ylabel('Sensibilidad (TPR)')
        axes[idx].set_title(f'Curva ROC - {diagnosis.upper()}')
        axes[idx].legend(loc="lower right")
        axes[idx].grid(alpha=0.3)
    
    output_path = os.path.join(output_dir, 'roc_curves.png')
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f'ROC curves saved to {output_path}')
    plt.close()


def calculate_metrics(predictions, labels, loss_weight=1.0, threshold=None, use_calculated_threshold=False):
    """Calculate all metrics for a single model."""
    
    # Ensure same length
    if len(predictions) != len(labels):
        min_len = min(len(predictions), len(labels))
        predictions = predictions[:min_len]
        labels = labels[:min_len]

    # Predictions are already probabilities from predict.py
    probs = predictions

    # Calculate AUC
    auc = metrics.roc_auc_score(labels, predictions)

    # Calculate Loss (BCEWithLogitsLoss)
    pos_weight = torch.tensor([loss_weight])
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    preds_tensor = torch.tensor(predictions, dtype=torch.float32)
    labels_tensor = torch.tensor(labels, dtype=torch.float32)
    loss = criterion(preds_tensor, labels_tensor).item()

    # Calculate threshold (optimal using Youden's J statistic)
    fpr, tpr, thresholds = metrics.roc_curve(labels, predictions)
    youden_j = tpr - fpr
    optimal_idx = np.argmax(youden_j)
    optimal_threshold = thresholds[optimal_idx]
    optimal_threshold_prob = optimal_threshold

    if use_calculated_threshold:
        decision_threshold = optimal_threshold_prob
    elif threshold is not None:
        decision_threshold = float(threshold)
    else:
        decision_threshold = 0.5

    # Get binary predictions using selected threshold on probabilities
    binary_preds = (probs >= decision_threshold).astype(int)

    # Calculate Sensitivity (True Positive Rate)
    sensitivity = metrics.recall_score(labels, binary_preds)

    # Calculate Specificity (True Negative Rate)
    tn, fp, fn, tp = metrics.confusion_matrix(labels, binary_preds).ravel()
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0

    # Calculate Accuracy
    accuracy = metrics.accuracy_score(labels, binary_preds)

    return {
        'auc': auc,
        'loss': loss,
        'sensitivity': sensitivity,
        'specificity': specificity,
        'accuracy': accuracy,
        'threshold': decision_threshold,
        'tp': tp,
        'tn': tn,
        'fp': fp,
        'fn': fn,
        'fpr': fpr,
        'tpr': tpr,
        'predictions': predictions,
        'labels': labels
    }


def main(valid_paths_csv, preds_csv, valid_labels_csv, loss_weight=1.0, output_dir='.', threshold=None, use_calculated_threshold=False):
    print('Reporting AUC scores and additional metrics...\n')

    preds_df = pd.read_csv(preds_csv, header=None)
    valid_df = pd.read_csv(valid_labels_csv)

    old_case = None

    cases = []
    with open(valid_paths_csv, 'r') as paths:
        for path in paths:
            case = os.path.splitext(os.path.basename(path.strip()))[0]
            if case == old_case:
                next
            else:
                cases.append(case)
                old_case = case

    ys = []
    Xs = []

    for i, case in enumerate(cases):
        case_row = valid_df[valid_df.case == int(case)]

        y = case_row.values[0,1:].astype(np.float32)
        ys.append(y)

        X = preds_df.iloc[i].values
        Xs.append(X)

    ys = np.asarray(ys).transpose()
    Xs = np.asarray(Xs).transpose()

    results = {}
    diagnoses = valid_df.columns.values[1:]

    print('=' * 120)
    print(f'{"Diagnosis":<15} {"AUC":<10} {"Loss":<10} {"Sensitivity":<15} {"Specificity":<15} {"Accuracy":<10} {"Threshold":<10}')
    print('=' * 120)

    for i, diagnosis in enumerate(diagnoses):
        metrics_dict = calculate_metrics(
            Xs[i],
            ys[i],
            loss_weight=loss_weight,
            threshold=threshold,
            use_calculated_threshold=use_calculated_threshold
        )
        results[diagnosis] = metrics_dict

        print(f'{diagnosis:<15} {metrics_dict["auc"]:<10.4f} {metrics_dict["loss"]:<10.4f} '
              f'{metrics_dict["sensitivity"]:<15.4f} {metrics_dict["specificity"]:<15.4f} '
              f'{metrics_dict["accuracy"]:<10.4f} {metrics_dict["threshold"]:<10.4f}')

    print('=' * 120)

    # Print detailed results
    print('\n\nDETAILED RESULTS:')
    print('=' * 120)

    for diagnosis in diagnoses:
        m = results[diagnosis]
        print(f'\n{diagnosis.upper()}:')
        print(f'  AUC:         {m["auc"]:.4f}')
        print(f'  Loss:        {m["loss"]:.4f}')
        print(f'  Sensitivity: {m["sensitivity"]:.4f}')
        print(f'  Specificity: {m["specificity"]:.4f}')
        print(f'  Accuracy:    {m["accuracy"]:.4f}')
        print(f'  Threshold:   {m["threshold"]:.4f}')
        print(f'  TP: {m["tp"]:<5} TN: {m["tn"]:<5} FP: {m["fp"]:<5} FN: {m["fn"]:<5}')

    # Generate ROC curves
    print('\n\nGenerating ROC curves...')
    plot_roc_curves(results, diagnoses, output_dir)

    # Summary statistics
    print('\n\n' + '=' * 120)
    print('SUMMARY STATISTICS:')
    print('=' * 120)

    if results:
        aucs = [m['auc'] for m in results.values()]
        losses = [m['loss'] for m in results.values()]
        sensitivities = [m['sensitivity'] for m in results.values()]
        specificities = [m['specificity'] for m in results.values()]
        accuracies = [m['accuracy'] for m in results.values()]

        print(f'AUC:         Mean: {np.mean(aucs):.4f} ± {np.std(aucs):.4f} | Min: {np.min(aucs):.4f} | Max: {np.max(aucs):.4f}')
        print(f'Loss:        Mean: {np.mean(losses):.4f} ± {np.std(losses):.4f} | Min: {np.min(losses):.4f} | Max: {np.max(losses):.4f}')
        print(f'Sensitivity: Mean: {np.mean(sensitivities):.4f} ± {np.std(sensitivities):.4f} | Min: {np.min(sensitivities):.4f} | Max: {np.max(sensitivities):.4f}')
        print(f'Specificity: Mean: {np.mean(specificities):.4f} ± {np.std(specificities):.4f} | Min: {np.min(specificities):.4f} | Max: {np.max(specificities):.4f}')
        print(f'Accuracy:    Mean: {np.mean(accuracies):.4f} ± {np.std(accuracies):.4f} | Min: {np.min(accuracies):.4f} | Max: {np.max(accuracies):.4f}')

    if results:
        excel_rows = []
        for diagnosis, metrics_dict in results.items():
            excel_rows.append({
                'diagnosis': diagnosis,
                'auc': metrics_dict['auc'],
                'loss': metrics_dict['loss'],
                'sensitivity': metrics_dict['sensitivity'],
                'specificity': metrics_dict['specificity'],
                'accuracy': metrics_dict['accuracy'],
                'threshold': metrics_dict['threshold'],
                'tp': metrics_dict['tp'],
                'tn': metrics_dict['tn'],
                'fp': metrics_dict['fp'],
                'fn': metrics_dict['fn']
            })

        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

        excel_path = os.path.join(output_dir, 'moremetrics_summary.xlsx')
        pd.DataFrame(excel_rows).to_excel(excel_path, index=False)
        print(f'Excel summary saved to {excel_path}')


if __name__ == '__main__':
    arguments = docopt(__doc__)

    print('Parsing arguments...')

    loss_weight = float(arguments['--loss-weight']) if arguments['--loss-weight'] is not None else 1.0
    output_dir = arguments['--output-dir'] if arguments['--output-dir'] is not None else '.'
    threshold = float(arguments['--threshold']) if arguments['--threshold'] is not None else None
    use_calculated_threshold = bool(arguments['--use-calculated-threshold'])

    main(arguments['<valid_paths_csv>'],
         arguments['<preds_csv>'],
         arguments['<valid_labels_csv>'],
         loss_weight,
         output_dir,
         threshold=threshold,
         use_calculated_threshold=use_calculated_threshold)
